import type { Offer } from "../store/context";

export const SEED_OFFERS: Offer[] = [
  {
    id: "of-001",
    title: "Développeur Full-Stack Junior",
    company: "Doctolib",
    location: "Paris",
    remote: "Hybride",
    contract: "CDI",
    salaryMin: 38000,
    salaryMax: 46000,
    platform: "Welcome to the Jungle",
    description:
      "Rejoins l'équipe produit pour construire les outils utilisés par 400 000 praticiens. Stack React/Ruby. Mentorat, code review, on forme sur l'archi.",
    skills: ["React", "TypeScript", "Ruby on Rails", "PostgreSQL", "Git"],
    postedDaysAgo: 2,
    url: "https://www.welcometothejungle.com/fr/jobs?query=d%C3%A9veloppeur%20junior&aroundQuery=Paris",
    highlight: "junior",
  },
  {
    id: "of-002",
    title: "Stage Data Analyst — 6 mois",
    company: "BlaBlaCar",
    location: "Paris",
    remote: "Hybride",
    contract: "Stage",
    salaryMin: 1300,
    salaryMax: 1500,
    platform: "Welcome to the Jungle",
    description:
      "Stage de 6 mois au sein de l'équipe Data. Tu travailleras sur les dashboards Looker, l'instrumentation produit et les analyses de cohorte.",
    skills: ["SQL", "Python", "Looker", "Statistiques", "Anglais"],
    postedDaysAgo: 1,
    url: "https://www.welcometothejungle.com/fr/jobs?query=stage%20data%20analyst&aroundQuery=Paris",
    highlight: "stage",
  },
  {
    id: "of-003",
    title: "Alternance Marketing Digital",
    company: "Back Market",
    location: "Bordeaux",
    remote: "Hybride",
    contract: "Alternance",
    salaryMin: 1200,
    salaryMax: 1700,
    platform: "HelloWork",
    description:
      "Tu rejoins l'équipe acquisition pour piloter les campagnes paid social (Meta, TikTok). Analyse, A/B test et création de contenus.",
    skills: ["Meta Ads", "TikTok Ads", "Excel", "Google Analytics", "Créativité"],
    postedDaysAgo: 5,
    url: "https://www.hellowork.com/fr-fr/emploi/recherche.html?k=alternance%20marketing%20digital&l=Bordeaux",
    highlight: "junior",
  },
  {
    id: "of-004",
    title: "Frontend Developer (React)",
    company: "Qonto",
    location: "Paris",
    remote: "Télétravail",
    contract: "CDI",
    salaryMin: 52000,
    salaryMax: 68000,
    platform: "LinkedIn",
    description:
      "Tu intégreras la squad Web pour faire évoluer le dashboard utilisé par 500k entrepreneurs européens. Architecture micro-frontend, design system maison.",
    skills: ["React", "TypeScript", "Storybook", "Jest", "GraphQL"],
    postedDaysAgo: 3,
    url: "https://www.linkedin.com/jobs/search/?keywords=frontend%20developer%20react&location=Paris%2C%20France",
    highlight: "remote",
  },
  {
    id: "of-005",
    title: "Customer Success Manager",
    company: "Aircall",
    location: "Lyon",
    remote: "Hybride",
    contract: "CDI",
    salaryMin: 42000,
    salaryMax: 50000,
    platform: "LinkedIn",
    description:
      "Tu portefeuilles 50 comptes SMB, identifies les opportunités d'upsell et coordonnes les équipes support et produit pour fidéliser.",
    skills: ["Relation client", "SaaS", "Anglais", "HubSpot", "Empathie"],
    postedDaysAgo: 7,
    url: "https://www.linkedin.com/jobs/search/?keywords=customer%20success%20manager&location=Lyon%2C%20France",
  },
  {
    id: "of-006",
    title: "Stage Product Design — UX/UI",
    company: "Alan",
    location: "Paris",
    remote: "Télétravail",
    contract: "Stage",
    salaryMin: 1400,
    salaryMax: 1600,
    platform: "Welcome to the Jungle",
    description:
      "6 mois aux côtés des designers seniors d'Alan. Tu contribueras aux flows d'onboarding et au design system. Mentorat hebdo.",
    skills: ["Figma", "Design System", "UX Research", "Prototypage", "Anglais"],
    postedDaysAgo: 1,
    url: "https://www.welcometothejungle.com/fr/jobs?query=stage%20product%20design",
    highlight: "stage",
  },
  {
    id: "of-007",
    title: "Assistant Commercial (H/F)",
    company: "Société générale",
    location: "Nantes",
    remote: "Sur site",
    contract: "CDD",
    salaryMin: 26000,
    salaryMax: 30000,
    platform: "APEC",
    description:
      "Tu accompagnes les conseillers patrimoniaux dans la préparation des dossiers clients, la prise de RDV et le suivi des opérations.",
    skills: ["Pack Office", "Rigueur", "Relation client", "Banque"],
    postedDaysAgo: 9,
    url: "https://www.apec.fr/candidat/recherche-emploi.html/emploi?motsCles=assistant%20commercial&lieux=72193",
  },
  {
    id: "of-008",
    title: "DevOps Engineer — Kubernetes",
    company: "Mirakl",
    location: "Paris",
    remote: "Télétravail",
    contract: "CDI",
    salaryMin: 60000,
    salaryMax: 80000,
    platform: "LinkedIn",
    description:
      "Tu construis la plateforme interne (IDP) sur Kubernetes. Pipelines GitLab, Terraform, observabilité Datadog.",
    skills: ["Kubernetes", "Terraform", "AWS", "GitLab CI", "Go"],
    postedDaysAgo: 4,
    url: "https://www.linkedin.com/jobs/search/?keywords=devops%20engineer%20kubernetes&location=France",
    highlight: "remote",
  },
  {
    id: "of-009",
    title: "Stage RH — Recrutement Tech",
    company: "PayFit",
    location: "Paris",
    remote: "Hybride",
    contract: "Stage",
    salaryMin: 1300,
    salaryMax: 1500,
    platform: "Welcome to the Jungle",
    description:
      "Tu sources des profils tech (sourcing LinkedIn, qualif tel), tu pilotes le pipeline ATS et tu participes aux events.",
    skills: ["Sourcing", "LinkedIn Recruiter", "Communication", "Anglais"],
    postedDaysAgo: 2,
    url: "https://www.welcometothejungle.com/fr/jobs?query=stage%20rh%20recrutement",
    highlight: "stage",
  },
  {
    id: "of-010",
    title: "Comptable Junior",
    company: "Mazars",
    location: "Lille",
    remote: "Hybride",
    contract: "CDI",
    salaryMin: 32000,
    salaryMax: 38000,
    platform: "APEC",
    description:
      "Cabinet d'audit international. Tu accompagnes les missions d'audit légal sur portefeuille PME-ETI, sous la supervision d'un manager.",
    skills: ["Comptabilité", "Excel", "Audit", "Rigueur"],
    postedDaysAgo: 12,
    url: "https://www.apec.fr/candidat/recherche-emploi.html/emploi?motsCles=comptable%20junior",
    highlight: "junior",
  },
  {
    id: "of-011",
    title: "Growth Hacker",
    company: "Spendesk",
    location: "Paris",
    remote: "Hybride",
    contract: "CDI",
    salaryMin: 45000,
    salaryMax: 60000,
    platform: "Welcome to the Jungle",
    description:
      "Tu rejoins la growth team. Mission : optimiser les funnels d'activation, scaler le SEO programmatique, automatiser l'outbound.",
    skills: ["SEO", "No-code", "Analytics", "Automation", "Python"],
    postedDaysAgo: 6,
    url: "https://www.welcometothejungle.com/fr/jobs?query=growth%20hacker",
  },
  {
    id: "of-012",
    title: "Mobile Developer iOS — Swift",
    company: "Veepee",
    location: "Paris",
    remote: "Hybride",
    contract: "CDI",
    salaryMin: 50000,
    salaryMax: 70000,
    platform: "Indeed",
    description:
      "Tu maintiens et fais évoluer l'app iOS (8M utilisateurs). Architecture MVVM-C, SwiftUI en cours d'adoption.",
    skills: ["Swift", "SwiftUI", "MVVM", "XCTest", "Combine"],
    postedDaysAgo: 8,
    url: "https://fr.indeed.com/jobs?q=d%C3%A9veloppeur%20iOS%20Swift&l=Paris",
  },
  {
    id: "of-013",
    title: "Stage Chef de Projet",
    company: "Decathlon",
    location: "Lille",
    remote: "Sur site",
    contract: "Stage",
    salaryMin: 1100,
    salaryMax: 1300,
    platform: "HelloWork",
    description:
      "Tu accompagnes les chefs de produit sur les nouvelles collections. Coordination usine, planning et reporting.",
    skills: ["Excel", "Gestion de projet", "Anglais", "Sport"],
    postedDaysAgo: 3,
    url: "https://www.hellowork.com/fr-fr/emploi/recherche.html?k=stage%20chef%20de%20projet&l=Lille",
    highlight: "stage",
  },
  {
    id: "of-014",
    title: "Data Engineer",
    company: "Criteo",
    location: "Paris",
    remote: "Hybride",
    contract: "CDI",
    salaryMin: 55000,
    salaryMax: 75000,
    platform: "LinkedIn",
    description:
      "Tu construis les pipelines de données qui alimentent le moteur d'enchères de Criteo. Stack Spark, Kafka, Airflow.",
    skills: ["Spark", "Kafka", "Airflow", "Python", "Scala"],
    postedDaysAgo: 4,
    url: "https://www.linkedin.com/jobs/search/?keywords=data%20engineer&location=Paris",
  },
  {
    id: "of-015",
    title: "Alternance Cybersécurité",
    company: "Thales",
    location: "Toulouse",
    remote: "Sur site",
    contract: "Alternance",
    salaryMin: 1200,
    salaryMax: 1600,
    platform: "France Travail",
    description:
      "Tu intègres l'équipe SOC. Analyse d'alertes, threat hunting, contribution aux playbooks SOAR.",
    skills: ["SIEM", "Linux", "Python", "Réseau", "Anglais"],
    postedDaysAgo: 10,
    url: "https://candidat.francetravail.fr/offres/recherche?motsCles=alternance%20cybers%C3%A9curit%C3%A9&lieux=31555",
    highlight: "junior",
  },
  {
    id: "of-016",
    title: "Designer Graphique Junior",
    company: "Le Slip Français",
    location: "Paris",
    remote: "Sur site",
    contract: "CDI",
    salaryMin: 30000,
    salaryMax: 36000,
    platform: "Welcome to the Jungle",
    description:
      "Tu crées les visuels print et digitaux : campagnes saisonnières, newsletters, packaging.",
    skills: ["Photoshop", "Illustrator", "Figma", "Branding", "InDesign"],
    postedDaysAgo: 6,
    url: "https://www.welcometothejungle.com/fr/jobs?query=designer%20graphique%20junior",
    highlight: "junior",
  },
  {
    id: "of-017",
    title: "Business Developer SaaS",
    company: "Lemlist",
    location: "Paris",
    remote: "Télétravail",
    contract: "CDI",
    salaryMin: 38000,
    salaryMax: 55000,
    platform: "LinkedIn",
    description:
      "Tu prospectes et closes des deals SMB sur le marché EMEA. Stack outbound moderne, commission attractive, équipe ambitieuse.",
    skills: ["Sales", "Outbound", "Anglais", "CRM", "Cold email"],
    postedDaysAgo: 5,
    url: "https://www.linkedin.com/jobs/search/?keywords=business%20developer%20saas",
    highlight: "remote",
  },
  {
    id: "of-018",
    title: "Stage Backend — Node.js / NestJS",
    company: "Swile",
    location: "Montpellier",
    remote: "Hybride",
    contract: "Stage",
    salaryMin: 1300,
    salaryMax: 1500,
    platform: "Welcome to the Jungle",
    description:
      "6 mois dans la squad Payments. Tu ajoutes des features sur l'API NestJS, écris les tests et participes aux code reviews.",
    skills: ["Node.js", "NestJS", "TypeScript", "PostgreSQL", "Tests"],
    postedDaysAgo: 1,
    url: "https://www.welcometothejungle.com/fr/jobs?query=stage%20backend%20nodejs",
    highlight: "stage",
  },
];

export function getSeedOffers(): Offer[] {
  return SEED_OFFERS;
}
